#!/usr/bin/env bash
# Upsert één "preview"-comment op een PR (marker-gebaseerd → geen comment-spam bij elke sync).
# Gebruik: pr-comment.sh <pr-nummer> <body>.  Vereist GH_TOKEN + GITHUB_REPOSITORY (GitHub Actions).
set -euo pipefail

PR="${1:?pr-nummer}"; BODY="${2:?body}"
REPO="${GITHUB_REPOSITORY:?zet GITHUB_REPOSITORY}"
MARKER="<!-- wetsanalyse-preview-env -->"

FULL="$(printf '%s\n%s\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_' "$MARKER" "$BODY")"

# Bestaande preview-comment (met de marker) zoeken.
CID="$(gh api "repos/$REPO/issues/$PR/comments" --paginate \
        -q ".[] | select(.body | contains(\"$MARKER\")) | .id" 2>/dev/null | head -n1 || true)"

if [ -n "${CID:-}" ]; then
  gh api -X PATCH "repos/$REPO/issues/comments/$CID" -f body="$FULL" >/dev/null
  echo "preview-comment bijgewerkt (id=$CID)"
else
  gh api -X POST "repos/$REPO/issues/$PR/comments" -f body="$FULL" >/dev/null
  echo "preview-comment aangemaakt"
fi
